---
version: "2.1"
services:
  calibre-web:
    image: johngong/calibre-web:0.6.20-5.44.0
    container_name: calibre-web
    environment:
      - UID=1000
      - GID=1000
      - TZ=Asia/Shanghai
      - ENABLE_CALIBRE_SERVER=true  #(true|false)设定开启calibre-server，默认开启
      - ENABLE_CALIBRE_SERVER_OPDS=false  #(true|false)开启calibre-server的OPDS功能，默认不开启，arm可能不可用
      - CALIBRE_SERVER_USER=admin  #calibre-server 用户名
      - CALIBRE_SERVER_PASSWORD=Admin@123  #calibre-server 用户密码
      - CALIBRE_SERVER_WEB_LANGUAGE=zh_CN #calibre-server web界面语言，详见calibre-server其它语言
      - CALIBRE_ASCII_FILENAME=true #(true|false)设定false时calibre支持中文目录
      - CALIBRE_WEB_LANGUAGE=zh_Hans_CN #(zh_Hans_CN|en)calibre-web初始界面语言，详见calibre-web其它语言
      - DISABLE_GOOGLE_SEARCH=false  #(true|false)设定禁用google搜索，默认不开启
      - DISABLE_SCHOLAR_SEARCH=false  #(true|false)设定禁用scholar搜索，默认不开启
      - ENABLE_CHOWN_LIBRARY=true #(true|false)设定修复library文件夹拥有者，默认开启
      - CALIBRE_LOCALHOST=true  #(true|false)设定从本地主机和本地网络加载封面，默认开启
    volumes:
      - ./config:/config  #calibre-web与calibre-server配置位置文件
      - ./library:/library #calibre-web与calibre-server书库默认位置
      - ./autoaddbooks:/autoaddbooks #calibre自动添加图书文件夹位置 (!!!配置autoaddbooks文件夹，图书添加后会自动删除)
    ports:
      - "8080:8080" #calibre-server web访问端口
      - "8083:8083" #calibre-web web访问端口,默认用户名: admin 默认密码: admin123
    restart: unless-stopped


# pwd: Admin@123
# ref: https://registry.hub.docker.com/r/johngong/calibre-web